name: macOS checks
on: [push, pull_request]
permissions:
  contents: read
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - run: ./script/package_release.sh
      - uses: actions/upload-artifact@v4
        with:
          name: Display-Boost-universal
          path: outputs/Display-Boost-universal.zip
